baseURL = "https://gongguowei.com/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "1024 CORES"
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-theme-luna"
timeout = 60_000
timeZone = "Asia/Shanghai"
enableGitInfo = false
hasCJKLanguage = true
paginate = 10
summaryLength = 50
canonifyURLs = false
relativeURLs = false
staticDir = ["static"]

[permalinks]
posts = "/:year/:month/:day/:slug.html"
pages = "/:slug.html"

[author]
name = "龚国玮"

[frontmatter]
lastmod = [":git", "lastmod", ":fileModTime", "date", "publishDate", ":default"]

[taxonomies]
tag = "tags"
category = "categories"

[imaging]
resampleFilter = "CatmullRom"
quality = 95
anchor = "smart"

[caches.getresource]
dir = ":resourceDir/_gen"
maxAge = "24h"

[privacy.googleAnalytics]
anonymizeIP = false

[privacy.youtube]
privacyEnhanced = true

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[["$manuMain"]]
name = "Home"
weight = 10
identifier = "home"
url = "/"

["$manuMain".params]
icon = "eva eva-home"

[["$manuMain"]]
name = "About"
weight = 20
identifier = "about"
url = "/about/"

["$manuMain".params]
icon = "eva eva-heart"

[["$manuMain"]]
name = "Links"
weight = 30
identifier = "links"
url = "/links/"

["$manuMain".params]
icon = "eva eva-people"

[["$manuMain"]]
name = "Archives"
weight = 40
identifier = "archives"
url = "/archives/"

["$manuMain".params]
icon = "eva eva-bar-chart"

[["$manuMain"]]
name = "Tags"
weight = 50
identifier = "tags"
url = "/tags/"

["$manuMain".params]
icon = "eva eva-hash"

[["$manuMain"]]
name = "Categories"
weight = 60
identifier = "categories"
url = "/categories/"

["$manuMain".params]
icon = "eva eva-folder"

[["$manuMain"]]
name = "Twitter"
weight = 70
identifier = "twitter"
url = "/twitter/"

["$manuMain".params]
icon = "eva eva-twitter"

[["$manuMain"]]
name = "GitHub"
weight = 80
identifier = "github"
url = "/github/"

["$manuMain".params]
icon = "eva eva-github"

[["$manuMain"]]
name = "Search"
weight = 999
identifier = "search"
url = "/search/"

["$manuMain".params]
icon = "eva eva-search"

[[menu.main]]
name = "Home"
weight = 10
identifier = "home"
url = "/"

[menu.main.params]
icon = "eva eva-home"

[[menu.main]]
name = "About"
weight = 20
identifier = "about"
url = "/about/"

[menu.main.params]
icon = "eva eva-heart"

[[menu.main]]
name = "Links"
weight = 30
identifier = "links"
url = "/links/"

[menu.main.params]
icon = "eva eva-people"

[[menu.main]]
name = "Archives"
weight = 40
identifier = "archives"
url = "/archives/"

[menu.main.params]
icon = "eva eva-bar-chart"

[[menu.main]]
name = "Twitter"
weight = 70
identifier = "twitter"
url = "/twitter/"

[menu.main.params]
icon = "eva eva-twitter"

[[menu.main]]
name = "GitHub"
weight = 80
identifier = "github"
url = "/github/"

[menu.main.params]
icon = "eva eva-github"

[[menu.main]]
name = "Search"
weight = 999
identifier = "search"
url = "/search/"

[menu.main.params]
icon = "eva eva-search"

[markup.highlight]
style = "dracula"
guessSyntax = true
tabWidth = 4
lineNumbersInTable = true
lineNos = true
codeFences = true

[markup.goldmark.renderer]
unsafe = true

[params]
publicCDN = ""
topTitle = false
sitemap = true
themeColor = "#2791e8"
blackAndWhite = false
headlineCounter = false
fixedNav = false
font = 'Roboto, "Helvetica Neue", Helvetica, Arial, sans-serif'
since = "2020"
autoDarkMode = false
qrcodeAPI = "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data="
i18nlist = true
imageZoom = true
lazyload = true
googleTranslate = false
pangu = true
search = true
lastmod = true
readingTime = true
wordCount = false
pjax = true
pwa = true
katex = true
backtop = true
featuredImageHeight = "42%"
defaultFeaturedImage = false
author = "GongGuowei"
keywords = ["Game", "Golang"]
description = "A simple, performance-first, SEO-friendly Hugo theme"

[params.announcement]
enabled = true
file = "README.md"

[params.comments]
enabled = true
provider = "giscus"

[params.comments.giscus]
repo = "guowei-gong/luna-comments"
repoID = "R_kgDOI-EiuQ"
category = "Announcements"
categoryID = "DIC_kwDOI-Eiuc4CUORj"
mapping = "title"
reactionsEnabled = 1
emitMetadata = 0
lazy = false
lang = "zh-CN"

[params.rss]
enabled = false
fullText = true

[params.console]
enabled = true
leftColor = "#dd6065"
leftText = "Hugo Theme Luna"
rightColor = "#feb462"
rightText = "Powered by Hugo 🧊 Luna"

[params.customScript]
enabled = false
pjax = true

[params.runTime]
enabled = true
creatTime = "2022/10/27"

[params.outdatedInfoWarning]
enabled = true
day = 90

[params.share]
twitter = true
facebook = true
weibo = true
copyLinkText = true
qrcode = true

[params.license]
enabled = true
name = "CC BY-NC-ND 4.0"
icon = "Cc-by-nc-nd.svg"
url = "https://creativecommons.org/licenses/by-nc-nd/4.0"

[params.github]
id = "guowei-gong"
minStars = 1

[params.twitter]
enabled = true
rsshub = "https://rsshub.rssforever.com"
id = "gongguowei01"
imageProcessing = true

[params.bionicReading]
enabled = true
autoBionic = false
skipLinks = false
excludeWords = []
excludeNodeNames = []
excludeClasses = ["github"]

[params.toc]
enabled = true
wordCount = 400

[params.HugoEncrypt]
Password = "123456"
Storage = "session"

[params.imageProcessing]
cover = true
content = true
autoResize = [1_080, 1_440]
webp = true

[params.opengraph]
image = "featured.png"

[params.opengraph.twitter]
cardType = "summary_large_image"
site = "@gongguowei01"

[build]
noJSConfigInAssets = true

[languages.zh-cn]
contentDir = "content/zh-hans"
languageName = "中文"

[languages.zh-cn.params]
languageIcon = "images/i18n/zh-cn.svg"
font = "Times New Roman,Times,Heti Song,serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol"

[languages.zh-cn.params.twitter]
enabled = true
rsshub = "https://rsshub.rssforever.com"
id = "gongguowei01"
imageProcessing = true

[languages.zh-cn.params.github]
id = "guowei-gong"
minStars = 1

[languages.zh-cn.params.license]
enabled = true
name = "署名 - 非商业性使用 - 禁止演绎 4.0"
icon = "Cc-by-nc-nd.svg"
url = "https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh"

[languages.zh-cn.params.announcement]
enabled = true
file = "README.zh.md"

[languages.zh-cn.params.comments]
enabled = true
provider = "giscus"

[languages.zh-cn.params.comments.giscus]
repo = "guowei-gong/luna-comments"
repoID = "R_kgDOI-EiuQ"
category = "Announcements"
categoryID = "DIC_kwDOI-Eiuc4CUORj"
mapping = "title"
reactionsEnabled = 1
emitMetadata = 0
lazy = false
lang = "zh-CN"
